"""
AGRI-WATT ESP32-S3 Weight & Quantization Exporter
Extracts trained MLP neural network weights and standard scaler parameters
and formats them as static C float arrays for direct execution by the ESP-NN vector engine.
"""

import os
import joblib
import numpy as np

def export_weights_to_c_header():
    base_dir = os.path.dirname(os.path.dirname(__file__))
    models_dir = os.path.join(base_dir, "models", "trained")
    firmware_dir = os.path.join(base_dir, "firmware", "main")
    
    mlp_clog_path = os.path.join(models_dir, "edge_mlp_clog_classifier.joblib")
    scaler_clog_path = os.path.join(models_dir, "clog_feature_scaler.joblib")
    
    mlp_et0_path = os.path.join(models_dir, "edge_mlp_et0_regressor.joblib")
    scaler_et0_path = os.path.join(models_dir, "et0_feature_scaler.joblib")
    
    if not os.path.exists(mlp_clog_path):
        raise FileNotFoundError("Trained models not found. Run train_models.py first.")
        
    mlp_clog = joblib.load(mlp_clog_path)
    scaler_clog = joblib.load(scaler_clog_path)
    
    mlp_et0 = joblib.load(mlp_et0_path)
    scaler_et0 = joblib.load(scaler_et0_path)
    
    header_content = """/*
 * AGRI-WATT: Auto-Generated Edge-AI Model Weights for ESP32-S3 ESP-NN
 * Generated by src/esp32_weight_exporter.py
 * Contains neural network layer weights, biases, and feature normalization vectors.
 */

#ifndef EDGE_AI_MODEL_WEIGHTS_H
#define EDGE_AI_MODEL_WEIGHTS_H

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================================
// MODEL 1: PRESSURE TRANSIENT CLOG DIAGNOSTIC CLASSIFIER
// Architecture: 5 Inputs -> 16 Dense (ReLU) -> 8 Dense (ReLU) -> 4 Classes (Softmax)
// Classes: 0: NORMAL, 1: PARTIAL_CLOG, 2: FULL_CLOG, 3: CAVITATION_LEAK
// ============================================================================

#define CLOG_INPUT_DIM      5
#define CLOG_HIDDEN1_DIM    16
#define CLOG_HIDDEN2_DIM    8
#define CLOG_OUTPUT_DIM     4

// Feature Normalization Parameters (StandardScaler)
"""
    # Append Clog Scaler
    header_content += f"static const float CLOG_FEATURE_MEANS[CLOG_INPUT_DIM] = {{"
    header_content += ", ".join([f"{v:.6f}f" for v in scaler_clog.mean_]) + "};\n"
    
    header_content += f"static const float CLOG_FEATURE_SCALES[CLOG_INPUT_DIM] = {{"
    header_content += ", ".join([f"{v:.6f}f" for v in scaler_clog.scale_]) + "};\n\n"
    
    # Layer 1 Weights & Biases (5 x 16)
    W1 = mlp_clog.coefs_[0]
    b1 = mlp_clog.intercepts_[0]
    header_content += "// Layer 1 Weights (5 x 16)\n"
    header_content += "static const float CLOG_W1[CLOG_INPUT_DIM][CLOG_HIDDEN1_DIM] = {\n"
    for row in W1:
        header_content += "    {" + ", ".join([f"{v:.6f}f" for v in row]) + "},\n"
    header_content += "};\n\n"
    
    header_content += "static const float CLOG_B1[CLOG_HIDDEN1_DIM] = {"
    header_content += ", ".join([f"{v:.6f}f" for v in b1]) + "};\n\n"
    
    # Layer 2 Weights & Biases (16 x 8)
    W2 = mlp_clog.coefs_[1]
    b2 = mlp_clog.intercepts_[1]
    header_content += "// Layer 2 Weights (16 x 8)\n"
    header_content += "static const float CLOG_W2[CLOG_HIDDEN1_DIM][CLOG_HIDDEN2_DIM] = {\n"
    for row in W2:
        header_content += "    {" + ", ".join([f"{v:.6f}f" for v in row]) + "},\n"
    header_content += "};\n\n"
    
    header_content += "static const float CLOG_B2[CLOG_HIDDEN2_DIM] = {"
    header_content += ", ".join([f"{v:.6f}f" for v in b2]) + "};\n\n"
    
    # Layer 3 Weights & Biases (8 x 4)
    W3 = mlp_clog.coefs_[2]
    b3 = mlp_clog.intercepts_[2]
    header_content += "// Layer 3 Weights (8 x 4)\n"
    header_content += "static const float CLOG_W3[CLOG_HIDDEN2_DIM][CLOG_OUTPUT_DIM] = {\n"
    for row in W3:
        header_content += "    {" + ", ".join([f"{v:.6f}f" for v in row]) + "},\n"
    header_content += "};\n\n"
    
    header_content += "static const float CLOG_B3[CLOG_OUTPUT_DIM] = {"
    header_content += ", ".join([f"{v:.6f}f" for v in b3]) + "};\n\n"
    
    # =========================================================================
    # MODEL 2: SOLAR MICROCLIMATE ET0 REGRESSOR
    # Architecture: 6 Inputs -> 16 Dense (ReLU) -> 8 Dense (ReLU) -> 1 Output
    # =========================================================================
    header_content += """// ============================================================================
// MODEL 2: SOLAR MICROCLIMATE FAO-56 ET0 PREDICTIVE REGRESSOR
// Architecture: 6 Inputs -> 16 Dense (ReLU) -> 8 Dense (ReLU) -> 1 Output (mm/day)
// ============================================================================

#define ET0_INPUT_DIM       6
#define ET0_HIDDEN1_DIM     16
#define ET0_HIDDEN2_DIM     8
#define ET0_OUTPUT_DIM      1

"""
    header_content += f"static const float ET0_FEATURE_MEANS[ET0_INPUT_DIM] = {{"
    header_content += ", ".join([f"{v:.6f}f" for v in scaler_et0.mean_]) + "};\n"
    
    header_content += f"static const float ET0_FEATURE_SCALES[ET0_INPUT_DIM] = {{"
    header_content += ", ".join([f"{v:.6f}f" for v in scaler_et0.scale_]) + "};\n\n"
    
    # ET0 Layer 1
    e_W1 = mlp_et0.coefs_[0]
    e_b1 = mlp_et0.intercepts_[0]
    header_content += "// ET0 Layer 1 Weights (6 x 16)\n"
    header_content += "static const float ET0_W1[ET0_INPUT_DIM][ET0_HIDDEN1_DIM] = {\n"
    for row in e_W1:
        header_content += "    {" + ", ".join([f"{v:.6f}f" for v in row]) + "},\n"
    header_content += "};\n\n"
    
    header_content += "static const float ET0_B1[ET0_HIDDEN1_DIM] = {"
    header_content += ", ".join([f"{v:.6f}f" for v in e_b1]) + "};\n\n"
    
    # ET0 Layer 2
    e_W2 = mlp_et0.coefs_[1]
    e_b2 = mlp_et0.intercepts_[1]
    header_content += "// ET0 Layer 2 Weights (16 x 8)\n"
    header_content += "static const float ET0_W2[ET0_HIDDEN1_DIM][ET0_HIDDEN2_DIM] = {\n"
    for row in e_W2:
        header_content += "    {" + ", ".join([f"{v:.6f}f" for v in row]) + "},\n"
    header_content += "};\n\n"
    
    header_content += "static const float ET0_B2[ET0_HIDDEN2_DIM] = {"
    header_content += ", ".join([f"{v:.6f}f" for v in e_b2]) + "};\n\n"
    
    # ET0 Layer 3
    e_W3 = mlp_et0.coefs_[2]
    e_b3 = mlp_et0.intercepts_[2]
    header_content += "// ET0 Layer 3 Weights (8 x 1)\n"
    header_content += "static const float ET0_W3[ET0_HIDDEN2_DIM][ET0_OUTPUT_DIM] = {\n"
    for row in e_W3:
        header_content += "    {" + ", ".join([f"{v:.6f}f" for v in row]) + "},\n"
    header_content += "};\n\n"
    
    header_content += "static const float ET0_B3[ET0_OUTPUT_DIM] = {"
    header_content += ", ".join([f"{v:.6f}f" for v in e_b3]) + "};\n\n"
    
    header_content += """#ifdef __cplusplus
}
#endif

#endif // EDGE_AI_MODEL_WEIGHTS_H
"""

    out_file1 = os.path.join(models_dir, "edge_ai_model_weights.h")
    with open(out_file1, "w") as f:
        f.write(header_content)
    print(f"[OK] Exported C Header to models: {out_file1}")
    
    out_file2 = os.path.join(firmware_dir, "edge_ai_model_weights.h")
    with open(out_file2, "w") as f:
        f.write(header_content)
    print(f"[OK] Exported C Header to firmware: {out_file2}")

if __name__ == '__main__':
    export_weights_to_c_header()
